export default Object.freeze({
  // Object.freeze prevent others from modifying it accidentally
  LISTING_DETAILS: "ListingDetails", //Caps means its a constant
  LISTINGS: "Feed",
  CATEGORY: "Search",
  LISTING_EDIT: "ListingEdit",
  ACCOUNT: "Account",
  WELCOME: "Welcome",
  MESSAGES: "My Support Tickets",
  PENDINGMESSAGES: "Pending Support Tickets",
  MESSAGESINPROGRESS: "Support in Progress",
  SUPPORTTICKET: "Support Ticket",
  LOGIN: "Login",
  REGISTER: "Register",
  CART: "Cart",
  AppNav: "AppNavigator",
  CartNav: "CartNavigator",
  SHOPPINGCART: "Shopping Cart",
  CHECKOUT: "Checkout",
  ORDERCONFIRMED: "Order Confirmed",
  GBCHECKOUT: "Checkout",
  GBORDERCONFIRMED: "Groupbuy Order Confirmed",
  LoginNav: "LoginNavigator",
  LISTINGSHISTORY: "My Listings",
  MERCHANTTOSHIP: "To Ship Orders",
  MERCHANTSHIPPED: "Shipped Orders",
  MERCHANTCOMPLETE: "Completed/Cancelled Orders",
  RECEIPT: "Receipt",
  MerchantOrdersNav: "Orders",
  EDITLISTING: "Edit Listing",
  EDITMILESTONE: "Group Buy Milestone Settings",
  FORGETPASSWORD: "Forget Password",
  ACCOUNTMANAGEMENT: "Edit Account Details",
  PAYMENTDETAILS: "Payment Details",
  SHIPPINGADDRESSES: "Shipping Addresses",
  ORDERHISTORY: "Order History",
  TOSHIP: "To Ship",
  COMPLETE: "Delivered",
  REFUND: "Refund",
  VOUCHERNAV: "Vouchers",
  CREATEMERVOUCHER: "Create Voucher",
  VIEWMERVOUCHER: "Store Vouchers",
  VIEWVOUCHER: "Vouchers",
  CATEGORIESVOUCHERS: "Categories Vouchers",
  STOREWIDEVOUCHERS: "Storewide Vouchers",
  MYGROUPBUYS: "My Group Buys",
  WATCHLIST: "Watchlist",
  MERCHANTREGISTER: " Merchant Registration",
  LOYALTY: "Group Buy Loyalty",
  FAQ: "FAQ",
});
